export default [
    {
        name: "Utah State University",
        logo: "https://i.pinimg.com/originals/96/65/d4/9665d4322a25b6a2ff8cc4f31a178749.png",
        link: "https://uwrl.usu.edu/",
        width: "210",
        height: "100",
    },
    {
        name: "The University of Vermont",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/UVMLogoSolid7484stacked-300x124.png",
        link: "https://www.uvm.edu/ciroh/",
        width: "210",
        height: "70",
    },
    {
        name: "University of Utah",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/University_of_Utah_horizontal_logo.svg/1280px-University_of_Utah_horizontal_logo.svg.png",
        link: "https://www.civil.utah.edu/",
        width: "210",
        height: "70",
    },
    {
        name: "The University of Alabama in Huntsville",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/UAH_primary-300x159.png",
        link: "https://www.itsc.uah.edu/home/projects/adapt-precipitation-super-resolution-and-data-fusion-deep-learning-techniques-operational-flood-forecasting",
        width: "190",
        height: "130",
    },
    {
        name: "University of California San Diego",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/UCSD-SIO_Vertical-Color_RGB.png",
        link: "https://cw3e.ucsd.edu/",
        width: "190",
        height: "75",
    },
    {
        name: "University of Arizona",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/ua_stack_rgb_4_0-300x281.png",
        link: "https://www.arizona.edu/",
        width: "105",
        height: "95",
    },
    {
        name: "University of Hawai'i at Mānoa",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/bottom-300x151.png",
        link: "https://manoa.hawaii.edu/",
        width: "190",
        height: "100",
    },
    {
        name: "University of Iowa",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/Block-IOWA-GOLD-ffcd00-1024x512.png",
        link: "https://www.uiowa.edu/",
        width: "160",
        height: "80",
    },
    {
        name: "University of Saskatchewan",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/usask_usask_colour-300x67.png",
        link: "https://water.usask.ca/",
        width: "190",
        height: "50",
    },
    {
        name: "University of Alabama",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/A-Square-Logo-4c_Official-300x300.jpg",
        link: "https://www.ua.edu/",
        width: "70",
        height: "70",
    },
    {
        name: "University of Minnesota",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/UMN_M-wdmk-stack-D2D-maroon-blk-300x237.png",
        link: "https://environment.umn.edu/",
        width: "170",
        height: "120",
    },
    {
        name: "Tuskegee University",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/tu_logo_OPTION-300x225.png",
        link: "https://www.tuskegee.edu/",
        width: "100",
        height: "100",
    },
    {
        name: "Bringham Young University",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/byu-wordmark-blue-300x191.png",
        link: "https://www.byu.edu/",
        width: "180",
        height: "100",
    },
    {
        name: "Colorado School Of Mines",
        logo: "https://ciroh.ua.edu/wp-content/uploads/2023/03/Mines-Stacked_1Color-blue-260x300.png",
        link: "https://ciroh.mines.edu/",
        width: "100",
        height: "120",
    },
];